### PR TITLE
email,url,ip format are now recognized

### PR DESCRIPTION
**Pull request by ismnoiet**
i've deleted my old forked repo, created a new one and applied all the required changes (because i had some problems with rebasing so i said why not building  it again from the scratch :) )

### CODE REVIEW

**Comment by mohsen1** [comment]
:+1: perfect!

**Comment by ismnoiet** [comment]
@mohsen1  Are you using any linter for this project(to get space after attribute name etc or it is just the convention and i'm ignorant ?

**Comment by mohsen1** [comment]
We have eslint https://github.com/mohsen1/json-to-json-schema/blob/master/.eslintrc

**Comment by ismnoiet** [comment]
So you are using eslint for this project(json-to-json-schema) ?

**Comment by mohsen1** [comment]
My editors picks up the eslintrc file automatically but you're right, it can be a pre step in the [build script](https://github.com/mohsen1/json-to-json-schema/blob/master/package.json#L17-L23).

**Comment by ismnoiet** [comment]
What code editor you're using, i'm using sublime text :)

**Pull request merged**
